name: Build & publish PDF

on:
  push:
    paths: ['**.tex', '**.bib']

jobs:
  latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_xelatex: true

      - uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: main.pdf

      - if: ${{ github.ref == 'refs/heads/main' && github.actor != 'github-actions[bot]' }}
        run: |
          git config user.name  "github-actions"
          git config user.email "github-actions@github.com"
          git add main.pdf
          git commit -m "chore(ci): auto-compiled PDF [skip ci]" || echo "No PDF changes"
          git push
